import 'package:flutter/cupertino.dart';

const siboh2 = SizedBox(height: 2);
const siboh4 = SizedBox(height: 4);
const siboh8 = SizedBox(height: 8);
const siboh10 = SizedBox(height: 10);
const siboh12 = SizedBox(height: 12);
const siboh16 = SizedBox(height: 16);
const siboh20 = SizedBox(height: 20);
const siboh24 = SizedBox(height: 24);
const siboh32 = SizedBox(height: 32);
const siboh64 = SizedBox(height: 64);
const siboh78 = SizedBox(height: 78);
const siboh90 = SizedBox(height: 90);
const siboh108 = SizedBox(height: 108);
const sibow2 = SizedBox(width: 2);
const sibow4 = SizedBox(width: 4);
const sibow8 = SizedBox(width: 8);
const sibow12 = SizedBox(width: 12);
const sibow16 = SizedBox(width: 16);
const sibow24 = SizedBox(width: 24);
const sibow32 = SizedBox(width: 32);
